version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: go-rabbitmq
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # Management UI port
      - '15674:15674' # Prometheus port
      - '61613:61613' # STOMP port
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data:
